const FrankDietrich = `<div class="title">FRANK DIETRICH</div>

<img src="./data/Csuri_RandomWar.jpg">

<div class="item">
    <div class="subtitle">Visual Intelligence: The First Decade of Computer Art (1965-1975)</div>

    <ul>
        <li>Bela Julesz</li>
        <li>A. Michael Noll</li>
        <li>Georg Nees</li>
        <li>Frieder Nake</li>
        <li>Manfred Schroeder</li>
        <li>Ken Knowlton</li>
        <li>Leon Harmon</li>
        <li>Frank Sinden</li>
        <li>E.E. Zajac</li>
        <li>Max Bense</li>
        <li>Peter Struycken</li>
        <li> G.M. Koenig</li>
        <li>Lejaren A. Hiller</li>
        <li>Robert A. Baker</li>
        <li>Iannas Xenakis</li>
        <li>Herbert Brün</li>
        <li>John Whitney</li>
        <li>Jasia Reichard</li>
        <li>Jack Burnham</li>
        <li>Robert Mallary</li>
        <li>Charles Csuri</li>
        <li>Groupe de Recherche d'Art Visuel, GRAV</li>
        <li>Vera Molnár</li>
        <li>Hiroshi Kawano</li>
        <li>Harold Cohen</li>
        <li>Manfred Mohr</li>
        <li>Edvard Zajec</li>
        <li>Duane Palyka</li>
        <li>Georg Nees</li>
        <li>Jack Citreon</li>
        <li>Stan Vanderbeek</li>
        <li>Lillian Schwarz</li>
        <li>Tom deFanti</li>
        <li>Klaus Basset</li>
        <li>Ivan Sutherland</li>
        <li>Ben F. Laposky</li>
        <li>Herbert W. Franke</li>
        <li>Leslie Mezei</li>
        <li>James Shaffer</li>
        <li>Japanese Computer Graphics Technique Group</li>
        <li>Sonia Landy Sheridan</li>
        <li>Colette e Charles Bangert</li>
    </ul>

    <ul>
        <li>Howard Wise Gallery</li>
        <li>Galerie Niedlich</li>
        <li>Bell Laboratories</li>
        <li>Technische Universität Stuttgart</li>
        <li>Instituut voor Sonologie, Rijks Universiteit</li>
        <li>University of Illinois</li>
        <li>"Cybernetic Serendipity", Institute of Contemporary Art</li>
        <li>"Some More Beginnings", Experiments in Art and Technology, Brooklyn Museum</li>
        <li> "Software", Jewish Museum</li>
        <li>Stanford University's Artificial Intelligence Laboratory</li>
        <li>IBM</li>
        <li>Ohio State University</li>
    </ul>

    <div class="text">
        "When we look at the handful of early computer art aficionados, certain patterns emerge. All scientists and
        artists in this group belong to the same generation, born between the two World Wars, approximately 1925-1940.
        Their heritage is not bound by national borders; rather it is international, representing the highly
        industrialized countries of Europe, North America and Japan."
    </div>

    <div class="text">
        "Conventional aesthetics and their social-psychological connotations were seen as a hindrance to creative visual
        research. It was precisely the computer's nonhumanness that was understood to free art from these influences."
    </div>

    <div class="text">
        "According to the Japanese artist Hiroshi Kawano, who started producing computer art in 1959, human standards of
        aesthetics are not applicable to computer art. Instead the works generated by a computer require from the artist
        (or critic) 'a rigorous stoicism against beauty.' For Kawano, the computer artist's only function is to teach
        the computer how to make art by programming an algorithm. Thus the artist/programmer has become a 'meta-artist,'
        and the executing artist could be the computer itself, the 'art-computer'."
    </div>

    <img src="./data/Kawano_Design2-1.jpg">

    <div class="text">
        "Methods of entering graphics were even more restricted. With hardly any interactive means of controlling the
        computer, artists had to rely on programs and predefined data. [...] Once the data was fed into the computer,
        there was no more creative invention. Therefore the design process took place exclusively in the
        conceptualization prior to running a program. [...] the first generation of computer artists had to focus on
        logic and mathematics — in short, rather abstract methods. To some degree this restriction brought about
        creative concepts derived directly from computer technology itself."
    </div>

    <div class="text">
        Manfred Mohr: "The paradox of my generative work is that formwise it is minimalist and contentwise it is
        maximalist."
    </div>

    <img src="./data/Mohr_P021-G.jpg">

    <div class="text">
        "The end of the first decade of computer art coincided with important changes due mainly to three technological
        advances:
        <ol type="1">
            <li>
                The invention of the microprocessor changed the size, price, and accessibility of computers
                dramatically. The computer could become a truly personal tool.
            </li>
            <li>
                Interactive systems became common in the creative process. Traditional paradigms of artistic creation
                such as painting and drawing, photographing and videotaping could be simulated on the computer.
            </li>
            <li>
                Raster graphics displays increased the complexity of imagery significantly. Bit-mapped image memories
                allowed virtually unlimited choice of color and thus supported the creation of smoothly shaded or
                textured three-dimensional images.
            </li>
        </ol>
        These three advances combined to foster the migration of computer technology into art schools and artists'
        studios as well as commercial production houses. The intimate collaboration between artists and scientists was
        no longer required. Supported by the emergence of user-friendly general-purpose and high-level graphics
        language, artists became computer literate, or they bought software off shelves stocked by a burgeoning compute
        graphics industry."
    </div>
</div>`;